import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { QuoteList } from "../components/list";
import styles from "../styles/Home.module.css";
import { IQuotes } from "../types";

const Home: NextPage = () => {
  const [quotes, setQuotes] = useState<IQuotes>([]);

  useEffect(() => {
    const getQuotes = async () => {
      const data = await fetch("/api/chuck");
      const quotesData = await data.json();
      setQuotes(quotesData);
    };
    getQuotes();
  }, []);

  console.log(quotes);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            <span>Chuck Norris Counter</span>
            <img
              className={styles.image}
              src="https://hemmabiotidningen.se/upload/news/large/Hemmabio270137587.jpg"
              alt="Chuck"
            />
          </h1>
        </div>
        <div>
          <QuoteList quotes={quotes} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

/*
export async function getServerSideProps() {
  const data = await fetch("api/chuck");
  const quotes = await data.json();
  return {
    props: { quotes },
  };
}
*/
